### ISSUE TITLE
cargo-ledger is missing Cargo.lock

### ISSUE THREAD

**Issue by dfordivam** [LedgerHQ/ledger-device-rust-sdk#126]
The `Cargo.lock` is missing from cargo-ledger and the README specifically mentions that it should be used.
Also the .cargo/config (`build-std`) also interferes with the build of cargo-ledger.

> Note that cargo's dependency resolver may behave differently when installing, and you may end up with errors. In order to fix those and force usage of the versions specified in the tagged Cargo.lock, append --locked to the above commands.

**Comment by yogh333** [comment]
Hello @dfordivam, could you please check this branch `jca/sdk_cleanup` regarding the Cargo.lock issue ?
Regarding the `.cargo/config` it should not interfere as cargo-ledger should be installed with a `stable` Rust toolchain.

**Comment by dfordivam** [comment]
@yogh333 Thanks, I have included a generated Cargo.lock in my branch already, and the cargo-ledger is working fine. Though I had to do a number of other tweaks. (ref: https://github.com/alamgu/ledger-nanos-sdk/commits/alamgu-fixes-new-sdk/)

**Comment by xchapron-ledger** [comment]
> @yogh333 Thanks, I have included a generated Cargo.lock in my branch already, and the cargo-ledger is working fine. Though I had to do a number of other tweaks. (ref: https://github.com/alamgu/ledger-nanos-sdk/commits/alamgu-fixes-new-sdk/)

Hello :)
Just to make it clear, I looked very quickly at the changes in your link, and I don't think we will deploy an app needing this.

**Comment by yogh333** [comment]
Hi @dfordivam, I have had also a look into your branch:

- Cargo.lock cab be included but as the SDK is organised as a workspace, the Cargo.lock shall be put at the root workspace (this is what I do in my branch)
-  Regarding the relocation we are also working on a solution that should be soon available (see https://github.com/LedgerHQ/ledger-device-rust-sdk/tree/feat/relocation)
- Regarding the use of `nightly`, it is mandatory and it impacts the use of cargo-ledger from our app-builder docer container only (as it depends on the check of an env variable only defined in our container). This container is used internally in our CI and also when deploying the app in the prodcution env. If the env variable `RUST_NIGHTLY` is not defined, then it has no impact as the default toolchain set in your env will be used.
- Same remark for target as we have a container where Nano targets have been already setup (see https://github.com/LedgerHQ/ledger-app-builder/blob/52f33c8e986fb516b0505641974111b4a3b8b83d/full/Dockerfile#L49)

 Hope it helps to understand ;)

**Comment by yogh333** [comment]
@dfordivam I also would like to emphasise about the fact that using as much as possible a build environment that is as close as possible to our build environment would ease PR merging, testing and deployment steps. So my advice is to have a look into the docker we are using to build, test and deploy device apps (https://github.com/LedgerHQ/ledger-app-builder). Using this docker is not mandatory but it might help you to setup your own env if you prefer to work natively.

**Comment by yogh333** [comment]
@dfordivam And last but not least, we have put in place a CI that is mandatory for any app and for any PR and branch merging in order to check if the app can be later deployed without any issue. You can see this CI here: https://github.com/LedgerHQ/app-boilerplate-rust/tree/main/.github/workflows. Please check the mandatory workflows:
- [coding_style_checks.yml](https://github.com/LedgerHQ/app-boilerplate-rust/blob/main/.github/workflows/coding_style_checks.yml)
- [guidelines_enforcer.yml](https://github.com/LedgerHQ/app-boilerplate-rust/blob/main/.github/workflows/guidelines_enforcer.yml)

but also [build_and_functional_tests.yml](https://github.com/LedgerHQ/app-boilerplate-rust/blob/main/.github/workflows/build_and_functional_tests.yml) which is highly recommended.

If you have any questions, do not hesitate.

**Comment by dfordivam** [comment]
Thanks all for your comments, I dont plan to use this branch for the apps, this is just for building cargo-ledger.
I will keep your points in mind while I do the upgrade of SDK in apps.
