### ISSUE TITLE
Add EdDSA signature creation via streaming for arbitrary size messages

### ISSUE THREAD

**Issue by dfordivam** [LedgerHQ/ledger-device-rust-sdk#137]
Certain blockchains (like Pocket) require signature of the entire message payload ( instead of the hash of the message). Doing such a signature generation for an arbitrary size message is not possible on the Ledger devices due to limited stack space. 

The only way to create signatures in limited stack space is by incrementally computing the SHA512 of the message.
Ref: https://datatracker.ietf.org/doc/html/rfc8032#page-13

The Ledger SDK must provide a way to compute EdDSA signature by consuming the message data incrementally, similar to the `Hash` interface.

A reference implementation is here https://github.com/alamgu/ledger-crypto-helpers/blob/8f46275fc7fe9b8169b4f689ce2a203fb02c993d/src/ed25519.rs#L72C6-L72C13

**Comment by yogh333** [comment]
@dfordivam We have a PR currently under review that that enables to compute a hash incrementally through `hash.update()` and `hash.final()` calls. Please have a look into #132

**Comment by dfordivam** [comment]
@yogh333 Doing hashing incrementally is already using existing cx_hash_update APIs, and is supported in our lib (https://github.com/alamgu/ledger-crypto-helpers/blob/develop/src/hasher.rs)
Hashing in of itself does not require ECPrivateKey.

Here I am referring to doing signing incrementally, which would be an operation/API of ECPrivateKey

**Comment by yhql** [comment]
Hello @dfordivam , sorry I don't know what incremental signing would be in that case, besides hashing messages as they arrive and calling `eddsa_sign_no_throw` as in our signing method here https://github.com/LedgerHQ/ledger-device-rust-sdk/blob/master/ledger_device_sdk/src/ecc.rs#L299 to finish up the signature. 
I see you perform the hash construction and scalar multiplication manually in `alamgu`, but this should be covered by `eddsa_sign` already, and I don't know what differs

**Comment by dfordivam** [comment]
@yhql  Let me clarify, the `eddsa_sign(hash(message))` != `eddsa_sign(message)`.
Typically one need to do sign on hash of message, which is straightforward to do for messages of arbitrary length.
But if the blockchain requires `eddsa_sign(message)`, then the size of message would be limited by the stack memory. Here I am referring to support of `eddsa_sign(message)` for messages of arbitrary length.
